name: Compile with Nuitka and Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk patchelf
          pip install nuitka
          

      - name: Build with Nuitka
        run: |
          python3 -m nuitka \
            --standalone \
            --onefile \
            --enable-plugin=tk-inter \
            --include-data-files=ico.png=ico.png \
            --linux-icon=ico.png \
            --remove-output \
            -o scrcpy-helper \
            scrcpy_helper.py  

      - name: Generate SHA-256 Checksum
        run: sha256sum scrcpy-helper > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            scrcpy-helper
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
